# Generated by Django 3.1.4 on 2021-02-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0010_auto_20210129_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='avijit',
            field=models.ImageField(blank=True, null=True, upload_to='owners/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='mousham',
            field=models.ImageField(blank=True, null=True, upload_to='owners/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='show_owner_info',
            field=models.BooleanField(default=True),
        ),
    ]
